SUPPLIERS = {
    "semiconductors": [
        {"name": "NVIDIA", "ticker": "NVDA", "rss": "https://nvidianews.nvidia.com/releases.xml", "tier": 1},
        {"name": "Intel", "ticker": "INTC", "rss": "https://newsroom.intel.com/feed/", "tier": 1},
        {"name": "AMD", "ticker": "AMD", "rss": "https://ir.amd.com/news-releases/rss", "tier": 1},
        {"name": "Qualcomm", "ticker": "QCOM", "rss": "https://www.qualcomm.com/news/rss", "tier": 1},
        {"name": "Broadcom", "ticker": "AVGO", "rss": None, "tier": 1},
        {"name": "TSMC", "ticker": "TSM", "rss": None, "tier": 1},
        {"name": "Texas Instruments", "ticker": "TXN", "rss": None, "tier": 2},
        {"name": "Analog Devices", "ticker": "ADI", "rss": None, "tier": 2},
        {"name": "Microchip Technology", "ticker": "MCHP", "rss": None, "tier": 2},
        {"name": "NXP Semiconductors", "ticker": "NXPI", "rss": None, "tier": 2},
        {"name": "STMicroelectronics", "ticker": "STM", "rss": None, "tier": 2},
        {"name": "Infineon Technologies", "ticker": "IFNNY", "rss": None, "tier": 2},
        {"name": "Renesas Electronics", "ticker": "RNECY", "rss": None, "tier": 2},
        {"name": "MediaTek", "ticker": "MDTKF", "rss": None, "tier": 2},
        {"name": "GlobalFoundries", "ticker": "GFS", "rss": None, "tier": 2},
        {"name": "onsemi", "ticker": "ON", "rss": None, "tier": 2},
        {"name": "Skyworks Solutions", "ticker": "SWKS", "rss": None, "tier": 2},
        {"name": "Qorvo", "ticker": "QRVO", "rss": None, "tier": 2},
        {"name": "Marvell Technology", "ticker": "MRVL", "rss": None, "tier": 2},
        {"name": "ASML", "ticker": "ASML", "rss": None, "tier": 1},
        {"name": "Applied Materials", "ticker": "AMAT", "rss": None, "tier": 1},
        {"name": "Lam Research", "ticker": "LRCX", "rss": None, "tier": 1},
        {"name": "KLA Corporation", "ticker": "KLAC", "rss": None, "tier": 1},
        {"name": "Tokyo Electron", "ticker": "TOELY", "rss": None, "tier": 2},
        {"name": "Synopsys", "ticker": "SNPS", "rss": None, "tier": 2},
        {"name": "Cadence Design Systems", "ticker": "CDNS", "rss": None, "tier": 2},
        {"name": "ARM Holdings", "ticker": "ARM", "rss": None, "tier": 1},
        {"name": "Allegro MicroSystems", "ticker": "ALGM", "rss": None, "tier": 3},
        {"name": "Diodes Incorporated", "ticker": "DIOD", "rss": None, "tier": 3},
        {"name": "Power Integrations", "ticker": "POWI", "rss": None, "tier": 3},
        {"name": "UMC", "ticker": "UMC", "rss": None, "tier": 3},
        {"name": "Tower Semiconductor", "ticker": "TSEM", "rss": None, "tier": 3},
        {"name": "Lattice Semiconductor", "ticker": "LSCC", "rss": None, "tier": 3},
        {"name": "Monolithic Power Systems", "ticker": "MPWR", "rss": None, "tier": 3},
        {"name": "Silicon Labs", "ticker": "SLAB", "rss": None, "tier": 3},
        {"name": "Semtech", "ticker": "SMTC", "rss": None, "tier": 3},
        {"name": "Cirrus Logic", "ticker": "CRUS", "rss": None, "tier": 3},
        {"name": "MACOM Technology", "ticker": "MTSI", "rss": None, "tier": 3},
        {"name": "Entegris", "ticker": "ENTG", "rss": None, "tier": 3},
        {"name": "Kulicke & Soffa", "ticker": "KLIC", "rss": None, "tier": 3},
        {"name": "MaxLinear", "ticker": "MXL", "rss": None, "tier": 3},
        {"name": "Wolfspeed", "ticker": "WOLF", "rss": None, "tier": 2},
        {"name": "Photronics", "ticker": "PLAB", "rss": None, "tier": 3},
        {"name": "Cohu", "ticker": "COHU", "rss": None, "tier": 3},
        {"name": "Axcelis Technologies", "ticker": "ACLS", "rss": None, "tier": 3},
        {"name": "PDF Solutions", "ticker": "PDFS", "rss": None, "tier": 3},
        {"name": "Onto Innovation", "ticker": "ONTO", "rss": None, "tier": 3},
        {"name": "Ultra Clean Holdings", "ticker": "UCTT", "rss": None, "tier": 3},
        {"name": "Ichor Holdings", "ticker": "ICHR", "rss": None, "tier": 3},
        {"name": "FormFactor", "ticker": "FORM", "rss": None, "tier": 3},
    ],
    "memory_storage": [
        {"name": "Samsung Electronics", "ticker": "SSNLF", "rss": "https://news.samsung.com/global/feed", "tier": 1},
        {"name": "SK Hynix", "ticker": "HXSCF", "rss": None, "tier": 1},
        {"name": "Micron Technology", "ticker": "MU", "rss": None, "tier": 1},
        {"name": "Western Digital", "ticker": "WDC", "rss": None, "tier": 2},
        {"name": "Seagate Technology", "ticker": "STX", "rss": None, "tier": 2},
        {"name": "Pure Storage", "ticker": "PSTG", "rss": None, "tier": 2},
        {"name": "NetApp", "ticker": "NTAP", "rss": None, "tier": 2},
        {"name": "Kingston Technology", "ticker": None, "rss": None, "tier": 2},
        {"name": "Kioxia", "ticker": None, "rss": None, "tier": 2},
        {"name": "Hitachi Vantara", "ticker": None, "rss": None, "tier": 3},
        {"name": "Transcend", "ticker": None, "rss": None, "tier": 3},
        {"name": "ADATA", "ticker": None, "rss": None, "tier": 3},
        {"name": "Phison Electronics", "ticker": None, "rss": None, "tier": 3},
        {"name": "Silicon Motion", "ticker": "SIMO", "rss": None, "tier": 3},
        {"name": "Solidigm", "ticker": None, "rss": None, "tier": 3},
        {"name": "VAST Data", "ticker": None, "rss": None, "tier": 2},
        {"name": "WekaIO", "ticker": None, "rss": None, "tier": 3},
        {"name": "DataCore Software", "ticker": None, "rss": None, "tier": 3},
    ],
    "networking": [
        {"name": "Cisco Systems", "ticker": "CSCO", "rss": "https://newsroom.cisco.com/feed/", "tier": 1},
        {"name": "Arista Networks", "ticker": "ANET", "rss": None, "tier": 1},
        {"name": "Palo Alto Networks", "ticker": "PANW", "rss": None, "tier": 1},
        {"name": "Juniper Networks", "ticker": "JNPR", "rss": None, "tier": 2},
        {"name": "Fortinet", "ticker": "FTNT", "rss": None, "tier": 2},
        {"name": "F5 Networks", "ticker": "FFIV", "rss": None, "tier": 2},
        {"name": "HPE Aruba", "ticker": "HPE", "rss": None, "tier": 2},
        {"name": "Nokia", "ticker": "NOK", "rss": "https://www.nokia.com/about-us/news/releases/feed/", "tier": 2},
        {"name": "Ericsson", "ticker": "ERIC", "rss": None, "tier": 2},
        {"name": "Extreme Networks", "ticker": "EXTR", "rss": None, "tier": 3},
        {"name": "CommScope", "ticker": "COMM", "rss": None, "tier": 2},
        {"name": "Ciena", "ticker": "CIEN", "rss": None, "tier": 2},
        {"name": "Lumentum", "ticker": "LITE", "rss": None, "tier": 3},
        {"name": "Viavi Solutions", "ticker": "VIAV", "rss": None, "tier": 3},
        {"name": "ADTRAN", "ticker": "ADTN", "rss": None, "tier": 3},
        {"name": "Calix", "ticker": "CALX", "rss": None, "tier": 3},
        {"name": "Ribbon Communications", "ticker": "RBBN", "rss": None, "tier": 3},
        {"name": "Cradlepoint", "ticker": None, "rss": None, "tier": 3},
        {"name": "Cambium Networks", "ticker": "CMBM", "rss": None, "tier": 3},
        {"name": "Spirent Communications", "ticker": "SPT", "rss": None, "tier": 3},
        {"name": "Netgear", "ticker": "NTGR", "rss": None, "tier": 3},
        {"name": "Ubiquiti", "ticker": "UI", "rss": None, "tier": 3},
        {"name": "Huawei", "ticker": None, "rss": None, "tier": 1},
        {"name": "ZTE", "ticker": None, "rss": None, "tier": 2},
        {"name": "Infinera", "ticker": "INFN", "rss": None, "tier": 3},
        {"name": "Sycamore Networks", "ticker": "SCMR", "rss": None, "tier": 3},
    ],
    "cloud_infrastructure": [
        {"name": "Amazon Web Services", "ticker": "AMZN", "rss": "https://aws.amazon.com/blogs/aws/feed/", "tier": 1},
        {"name": "Microsoft Azure", "ticker": "MSFT", "rss": "https://azure.microsoft.com/en-us/blog/feed/", "tier": 1},
        {"name": "Google Cloud", "ticker": "GOOGL", "rss": "https://cloud.google.com/feeds/gcp-release-notes.xml", "tier": 1},
        {"name": "Cloudflare", "ticker": "NET", "rss": "https://blog.cloudflare.com/rss/", "tier": 1},
        {"name": "CoreWeave", "ticker": None, "rss": None, "tier": 1},
        {"name": "Oracle Cloud", "ticker": "ORCL", "rss": None, "tier": 2},
        {"name": "IBM Cloud", "ticker": "IBM", "rss": None, "tier": 2},
        {"name": "Fastly", "ticker": "FSLY", "rss": None, "tier": 2},
        {"name": "Akamai", "ticker": "AKAM", "rss": None, "tier": 2},
        {"name": "DigitalOcean", "ticker": "DOCN", "rss": None, "tier": 2},
        {"name": "Lambda Labs", "ticker": None, "rss": None, "tier": 2},
        {"name": "Vultr", "ticker": None, "rss": None, "tier": 3},
        {"name": "Hetzner", "ticker": None, "rss": None, "tier": 3},
        {"name": "OVHcloud", "ticker": "OVH", "rss": None, "tier": 3},
        {"name": "Equinix", "ticker": "EQIX", "rss": None, "tier": 1},
        {"name": "Digital Realty", "ticker": "DLR", "rss": None, "tier": 2},
        {"name": "Iron Mountain", "ticker": "IRM", "rss": None, "tier": 2},
        {"name": "CyrusOne", "ticker": None, "rss": None, "tier": 3},
        {"name": "Linode (Akamai)", "ticker": "AKAM", "rss": None, "tier": 3},
        {"name": "Fly.io", "ticker": None, "rss": None, "tier": 3},
        {"name": "Render", "ticker": None, "rss": None, "tier": 3},
        {"name": "Cloudinary", "ticker": None, "rss": None, "tier": 3},
        {"name": "Fastly", "ticker": "FSLY", "rss": None, "tier": 2},
    ],
    "servers_hardware": [
        {"name": "Dell Technologies", "ticker": "DELL", "rss": "https://www.dell.com/en-us/blog/feed/", "tier": 1},
        {"name": "HPE", "ticker": "HPE", "rss": None, "tier": 1},
        {"name": "Supermicro", "ticker": "SMCI", "rss": None, "tier": 1},
        {"name": "HP Inc", "ticker": "HPQ", "rss": None, "tier": 2},
        {"name": "Lenovo", "ticker": "LNVGY", "rss": None, "tier": 2},
        {"name": "Fujitsu", "ticker": "FJTSY", "rss": None, "tier": 2},
        {"name": "Inspur", "ticker": None, "rss": None, "tier": 2},
        {"name": "Hitachi", "ticker": "HTHIY", "rss": None, "tier": 2},
        {"name": "NEC", "ticker": "NIPNF", "rss": None, "tier": 3},
        {"name": "Gigabyte Technology", "ticker": None, "rss": None, "tier": 3},
        {"name": "ASRock Rack", "ticker": None, "rss": None, "tier": 3},
        {"name": "Wiwynn", "ticker": None, "rss": None, "tier": 3},
        {"name": "QCT (Quanta Cloud)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Asus", "ticker": "ASUUY", "rss": None, "tier": 3},
        {"name": "Penguin Computing", "ticker": None, "rss": None, "tier": 3},
        {"name": "Cray (HPE)", "ticker": "HPE", "rss": None, "tier": 2},
        {"name": "Inventec", "ticker": None, "rss": None, "tier": 3},
        {"name": "MiTAC Holdings", "ticker": None, "rss": None, "tier": 3},
    ],
    "contract_manufacturing": [
        {"name": "Foxconn", "ticker": "HNHPF", "rss": None, "tier": 1},
        {"name": "Pegatron", "ticker": None, "rss": None, "tier": 2},
        {"name": "Quanta Computer", "ticker": "QUCPF", "rss": None, "tier": 2},
        {"name": "Compal Electronics", "ticker": None, "rss": None, "tier": 2},
        {"name": "Wistron", "ticker": None, "rss": None, "tier": 2},
        {"name": "Jabil", "ticker": "JBL", "rss": None, "tier": 2},
        {"name": "Flex Ltd", "ticker": "FLEX", "rss": None, "tier": 2},
        {"name": "Celestica", "ticker": "CLS", "rss": None, "tier": 2},
        {"name": "Sanmina", "ticker": "SANM", "rss": None, "tier": 3},
        {"name": "Benchmark Electronics", "ticker": "BHE", "rss": None, "tier": 3},
        {"name": "Plexus Corp", "ticker": "PLXS", "rss": None, "tier": 3},
        {"name": "Fabrinet", "ticker": "FN", "rss": None, "tier": 3},
        {"name": "Entorian Technologies", "ticker": None, "rss": None, "tier": 3},
        {"name": "IEC Electronics", "ticker": "IEC", "rss": None, "tier": 3},
        {"name": "Key Tronic", "ticker": "KTCC", "rss": None, "tier": 3},
        {"name": "SIIX Corporation", "ticker": None, "rss": None, "tier": 3},
        {"name": "Venture Corporation", "ticker": None, "rss": None, "tier": 3},
    ],
    "cables_connectors": [
        {"name": "Amphenol", "ticker": "APH", "rss": None, "tier": 2},
        {"name": "TE Connectivity", "ticker": "TEL", "rss": None, "tier": 2},
        {"name": "Molex", "ticker": None, "rss": None, "tier": 2},
        {"name": "Samtec", "ticker": None, "rss": None, "tier": 3},
        {"name": "Hirose Electric", "ticker": "HRELF", "rss": None, "tier": 3},
        {"name": "Phoenix Contact", "ticker": None, "rss": None, "tier": 3},
        {"name": "Belden", "ticker": "BDC", "rss": None, "tier": 3},
        {"name": "Panduit", "ticker": None, "rss": None, "tier": 3},
        {"name": "Bourns", "ticker": None, "rss": None, "tier": 3},
        {"name": "Vishay Intertechnology", "ticker": "VSH", "rss": None, "tier": 3},
        {"name": "Molex", "ticker": None, "rss": None, "tier": 2},
        {"name": "Harting", "ticker": None, "rss": None, "tier": 3},
        {"name": "Deutsch (TE)", "ticker": "TEL", "rss": None, "tier": 3},
        {"name": "Radiall", "ticker": None, "rss": None, "tier": 3},
        {"name": "Rosenberger", "ticker": None, "rss": None, "tier": 3},
    ],
    "power_energy": [
        {"name": "Schneider Electric", "ticker": "SBGSF", "rss": None, "tier": 1},
        {"name": "Vertiv", "ticker": "VRT", "rss": None, "tier": 1},
        {"name": "Eaton", "ticker": "ETN", "rss": None, "tier": 2},
        {"name": "ABB", "ticker": "ABB", "rss": None, "tier": 2},
        {"name": "Delta Electronics", "ticker": "DELTF", "rss": None, "tier": 2},
        {"name": "Emerson Electric", "ticker": "EMR", "rss": None, "tier": 2},
        {"name": "General Electric", "ticker": "GE", "rss": None, "tier": 2},
        {"name": "Siemens Energy", "ticker": "SMNEY", "rss": None, "tier": 2},
        {"name": "Bel Fuse", "ticker": "BELFA", "rss": None, "tier": 3},
        {"name": "Vicor Corporation", "ticker": "VICR", "rss": None, "tier": 3},
        {"name": "Mean Well", "ticker": None, "rss": None, "tier": 3},
        {"name": "Acuity Brands", "ticker": "AYI", "rss": None, "tier": 3},
        {"name": "EnerSys", "ticker": "ENS", "rss": None, "tier": 3},
        {"name": "Tripp Lite (Eaton)", "ticker": "ETN", "rss": None, "tier": 3},
        {"name": "SL Power Electronics", "ticker": None, "rss": None, "tier": 3},
    ],
    "test_measurement": [
        {"name": "Keysight Technologies", "ticker": "KEYS", "rss": None, "tier": 2},
        {"name": "Teradyne", "ticker": "TER", "rss": None, "tier": 2},
        {"name": "National Instruments (NI)", "ticker": "NATI", "rss": None, "tier": 2},
        {"name": "Rohde & Schwarz", "ticker": None, "rss": None, "tier": 2},
        {"name": "Advantest", "ticker": "ATEYY", "rss": None, "tier": 3},
        {"name": "Anritsu", "ticker": None, "rss": None, "tier": 3},
        {"name": "Cohu", "ticker": "COHU", "rss": None, "tier": 3},
        {"name": "Spirent Communications", "ticker": "SPT", "rss": None, "tier": 3},
        {"name": "Tektronix (Fortive)", "ticker": "FTV", "rss": None, "tier": 2},
        {"name": "Fluke (Fortive)", "ticker": "FTV", "rss": None, "tier": 3},
        {"name": "Danaher", "ticker": "DHR", "rss": None, "tier": 2},
        {"name": "Yokogawa Electric", "ticker": "YOKEY", "rss": None, "tier": 3},
    ],
    "cybersecurity": [
        {"name": "CrowdStrike", "ticker": "CRWD", "rss": "https://www.crowdstrike.com/blog/feed/", "tier": 1},
        {"name": "SentinelOne", "ticker": "S", "rss": None, "tier": 1},
        {"name": "Zscaler", "ticker": "ZS", "rss": None, "tier": 1},
        {"name": "Okta", "ticker": "OKTA", "rss": None, "tier": 1},
        {"name": "Palo Alto Networks", "ticker": "PANW", "rss": None, "tier": 1},
        {"name": "Check Point Software", "ticker": "CHKP", "rss": None, "tier": 2},
        {"name": "Fortinet", "ticker": "FTNT", "rss": None, "tier": 2},
        {"name": "Varonis Systems", "ticker": "VRNS", "rss": None, "tier": 2},
        {"name": "Tenable Holdings", "ticker": "TENB", "rss": None, "tier": 2},
        {"name": "Rapid7", "ticker": "RPD", "rss": None, "tier": 2},
        {"name": "Qualys", "ticker": "QLYS", "rss": None, "tier": 2},
        {"name": "Darktrace", "ticker": "DARK", "rss": None, "tier": 2},
        {"name": "CyberArk Software", "ticker": "CYBR", "rss": None, "tier": 2},
        {"name": "Proofpoint", "ticker": None, "rss": None, "tier": 2},
        {"name": "Mimecast", "ticker": None, "rss": None, "tier": 2},
        {"name": "KnowBe4", "ticker": None, "rss": None, "tier": 3},
        {"name": "Recorded Future", "ticker": None, "rss": None, "tier": 2},
        {"name": "Illumio", "ticker": None, "rss": None, "tier": 3},
        {"name": "Wiz", "ticker": None, "rss": None, "tier": 1},
        {"name": "Orca Security", "ticker": None, "rss": None, "tier": 2},
        {"name": "Lacework", "ticker": None, "rss": None, "tier": 2},
        {"name": "Snyk", "ticker": None, "rss": None, "tier": 2},
        {"name": "Veracode", "ticker": None, "rss": None, "tier": 3},
        {"name": "Tanium", "ticker": None, "rss": None, "tier": 2},
        {"name": "Axonius", "ticker": None, "rss": None, "tier": 2},
        {"name": "Hunters", "ticker": None, "rss": None, "tier": 3},
    ],
    "optical_fiber": [
        {"name": "Corning", "ticker": "GLW", "rss": None, "tier": 2},
        {"name": "Prysmian", "ticker": "PRYMF", "rss": None, "tier": 2},
        {"name": "CommScope", "ticker": "COMM", "rss": None, "tier": 2},
        {"name": "Coherent Corp", "ticker": "COHR", "rss": None, "tier": 2},
        {"name": "Sumitomo Electric", "ticker": "SMTOF", "rss": None, "tier": 3},
        {"name": "Nexans", "ticker": "NEXNY", "rss": None, "tier": 3},
        {"name": "Furukawa Electric", "ticker": "FUWAY", "rss": None, "tier": 3},
        {"name": "Fujikura", "ticker": None, "rss": None, "tier": 3},
        {"name": "Leoni", "ticker": None, "rss": None, "tier": 3},
        {"name": "OFS (Furukawa)", "ticker": None, "rss": None, "tier": 3},
        {"name": "II-VI (Coherent)", "ticker": "COHR", "rss": None, "tier": 2},
    ],
    "cooling_thermal": [
        {"name": "Vertiv", "ticker": "VRT", "rss": None, "tier": 1},
        {"name": "Schneider Electric", "ticker": "SBGSF", "rss": None, "tier": 1},
        {"name": "Nidec Corporation", "ticker": "NJDCY", "rss": None, "tier": 3},
        {"name": "Delta Electronics", "ticker": "DELTF", "rss": None, "tier": 2},
        {"name": "Boyd Corporation", "ticker": None, "rss": None, "tier": 3},
        {"name": "Laird Thermal Systems", "ticker": None, "rss": None, "tier": 3},
        {"name": "Liqtech International", "ticker": "LIQT", "rss": None, "tier": 3},
        {"name": "CoolIT Systems", "ticker": None, "rss": None, "tier": 3},
        {"name": "Green Revolution Cooling", "ticker": None, "rss": None, "tier": 3},
        {"name": "Submer Technologies", "ticker": None, "rss": None, "tier": 3},
        {"name": "Asetek", "ticker": "ASTEK", "rss": None, "tier": 3},
        {"name": "Aavid Thermal", "ticker": None, "rss": None, "tier": 3},
        {"name": "Wakefield-Vette", "ticker": None, "rss": None, "tier": 3},
    ],
    "distributors_resellers": [
        {"name": "Arrow Electronics", "ticker": "ARW", "rss": None, "tier": 1},
        {"name": "Avnet", "ticker": "AVT", "rss": None, "tier": 1},
        {"name": "TD SYNNEX", "ticker": "SNX", "rss": None, "tier": 1},
        {"name": "Ingram Micro", "ticker": None, "rss": None, "tier": 1},
        {"name": "CDW Corporation", "ticker": "CDW", "rss": None, "tier": 2},
        {"name": "Insight Direct", "ticker": "NSIT", "rss": None, "tier": 2},
        {"name": "SHI International", "ticker": None, "rss": None, "tier": 2},
        {"name": "Wesco International", "ticker": "WCC", "rss": None, "tier": 2},
        {"name": "Digi-Key Electronics", "ticker": None, "rss": None, "tier": 2},
        {"name": "Mouser Electronics", "ticker": None, "rss": None, "tier": 2},
        {"name": "Newark (Farnell)", "ticker": None, "rss": None, "tier": 3},
        {"name": "RS Components", "ticker": None, "rss": None, "tier": 3},
        {"name": "Future Electronics", "ticker": None, "rss": None, "tier": 3},
        {"name": "TTI Inc", "ticker": None, "rss": None, "tier": 3},
        {"name": "Synnex (Concentrix)", "ticker": "CNXC", "rss": None, "tier": 2},
        {"name": "Microland", "ticker": None, "rss": None, "tier": 3},
        {"name": "PCM (Insight)", "ticker": "NSIT", "rss": None, "tier": 3},
    ],
    "enterprise_software": [
        {"name": "Microsoft", "ticker": "MSFT", "rss": "https://news.microsoft.com/feed/", "tier": 1},
        {"name": "SAP", "ticker": "SAP", "rss": None, "tier": 1},
        {"name": "Oracle", "ticker": "ORCL", "rss": None, "tier": 1},
        {"name": "Salesforce", "ticker": "CRM", "rss": None, "tier": 1},
        {"name": "ServiceNow", "ticker": "NOW", "rss": None, "tier": 1},
        {"name": "Workday", "ticker": "WDAY", "rss": None, "tier": 2},
        {"name": "Adobe", "ticker": "ADBE", "rss": None, "tier": 2},
        {"name": "Autodesk", "ticker": "ADSK", "rss": None, "tier": 2},
        {"name": "PTC", "ticker": "PTC", "rss": None, "tier": 3},
        {"name": "Dassault Systemes", "ticker": "DASTY", "rss": None, "tier": 3},
        {"name": "ANSYS", "ticker": "ANSS", "rss": None, "tier": 3},
        {"name": "Atlassian", "ticker": "TEAM", "rss": None, "tier": 2},
        {"name": "Slack (Salesforce)", "ticker": "CRM", "rss": None, "tier": 2},
        {"name": "Zoom", "ticker": "ZM", "rss": None, "tier": 2},
        {"name": "DocuSign", "ticker": "DOCU", "rss": None, "tier": 3},
        {"name": "Box", "ticker": "BOX", "rss": None, "tier": 3},
        {"name": "Dropbox", "ticker": "DBX", "rss": None, "tier": 3},
        {"name": "HubSpot", "ticker": "HUBS", "rss": None, "tier": 2},
        {"name": "Zendesk", "ticker": None, "rss": None, "tier": 3},
        {"name": "Freshworks", "ticker": "FRSH", "rss": None, "tier": 3},
    ],
    "industrial_automation": [
        {"name": "Siemens", "ticker": "SIEGY", "rss": "https://press.siemens.com/global/en/pressreleases/rss", "tier": 1},
        {"name": "ABB", "ticker": "ABB", "rss": None, "tier": 1},
        {"name": "Rockwell Automation", "ticker": "ROK", "rss": None, "tier": 2},
        {"name": "Honeywell", "ticker": "HON", "rss": None, "tier": 2},
        {"name": "Emerson Electric", "ticker": "EMR", "rss": None, "tier": 2},
        {"name": "Fanuc", "ticker": "FANUY", "rss": None, "tier": 2},
        {"name": "Keyence", "ticker": "KYCCF", "rss": None, "tier": 2},
        {"name": "Cognex", "ticker": "CGNX", "rss": None, "tier": 3},
        {"name": "Zebra Technologies", "ticker": "ZBRA", "rss": None, "tier": 3},
        {"name": "Advantech", "ticker": "ATECF", "rss": None, "tier": 3},
        {"name": "Yokogawa Electric", "ticker": "YOKEY", "rss": None, "tier": 3},
        {"name": "Bosch Rexroth", "ticker": None, "rss": None, "tier": 2},
        {"name": "Mitsubishi Electric", "ticker": "MIELY", "rss": None, "tier": 2},
        {"name": "Omron", "ticker": "OMRNY", "rss": None, "tier": 3},
        {"name": "Beckhoff Automation", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_foundation_labs": [
        {"name": "Anthropic", "ticker": None, "rss": "https://www.anthropic.com/rss.xml", "tier": 1},
        {"name": "OpenAI", "ticker": None, "rss": "https://openai.com/blog/rss.xml", "tier": 1},
        {"name": "Google DeepMind", "ticker": "GOOGL", "rss": "https://deepmind.google/blog/rss.xml", "tier": 1},
        {"name": "Meta AI", "ticker": "META", "rss": "https://ai.meta.com/blog/rss/", "tier": 1},
        {"name": "Mistral AI", "ticker": None, "rss": "https://mistral.ai/news/rss", "tier": 1},
        {"name": "xAI (Grok)", "ticker": None, "rss": None, "tier": 1},
        {"name": "Cohere", "ticker": None, "rss": None, "tier": 1},
        {"name": "AI21 Labs", "ticker": None, "rss": None, "tier": 2},
        {"name": "Inflection AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Aleph Alpha", "ticker": None, "rss": None, "tier": 2},
        {"name": "Technology Innovation Institute", "ticker": None, "rss": None, "tier": 2},
        {"name": "Baidu AI", "ticker": "BIDU", "rss": None, "tier": 2},
        {"name": "Alibaba DAMO", "ticker": "BABA", "rss": None, "tier": 2},
        {"name": "Tencent AI Lab", "ticker": "TCEHY", "rss": None, "tier": 2},
        {"name": "Samsung Research", "ticker": "SSNLF", "rss": None, "tier": 2},
    ],
    "ai_infrastructure_chips": [
        {"name": "Groq", "ticker": None, "rss": None, "tier": 1},
        {"name": "Cerebras Systems", "ticker": None, "rss": None, "tier": 1},
        {"name": "Tenstorrent", "ticker": None, "rss": None, "tier": 1},
        {"name": "SambaNova Systems", "ticker": None, "rss": None, "tier": 2},
        {"name": "Graphcore", "ticker": None, "rss": None, "tier": 2},
        {"name": "d-Matrix", "ticker": None, "rss": None, "tier": 2},
        {"name": "Etched", "ticker": None, "rss": None, "tier": 2},
        {"name": "Hailo Technologies", "ticker": None, "rss": None, "tier": 2},
        {"name": "Rain AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Kneron", "ticker": None, "rss": None, "tier": 3},
        {"name": "Untether AI", "ticker": None, "rss": None, "tier": 3},
        {"name": "Mythic", "ticker": None, "rss": None, "tier": 3},
        {"name": "BrainChip Holdings", "ticker": "BRCHF", "rss": None, "tier": 3},
        {"name": "Esperanto Technologies", "ticker": None, "rss": None, "tier": 3},
        {"name": "Amazon Trainium (AWS)", "ticker": "AMZN", "rss": None, "tier": 1},
        {"name": "Google TPU", "ticker": "GOOGL", "rss": None, "tier": 1},
        {"name": "Microsoft Maia", "ticker": "MSFT", "rss": None, "tier": 1},
    ],
    "ai_agents_orchestration": [
        {"name": "LangChain", "ticker": None, "rss": "https://blog.langchain.dev/rss/", "tier": 1},
        {"name": "LlamaIndex", "ticker": None, "rss": None, "tier": 1},
        {"name": "CrewAI", "ticker": None, "rss": None, "tier": 1},
        {"name": "AutoGen (Microsoft)", "ticker": "MSFT", "rss": None, "tier": 1},
        {"name": "Relevance AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Beam AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Dust", "ticker": None, "rss": None, "tier": 2},
        {"name": "Wordware", "ticker": None, "rss": None, "tier": 2},
        {"name": "Superagent", "ticker": None, "rss": None, "tier": 3},
        {"name": "Flowise", "ticker": None, "rss": None, "tier": 3},
        {"name": "Botpress", "ticker": None, "rss": None, "tier": 3},
        {"name": "Dify", "ticker": None, "rss": None, "tier": 2},
        {"name": "n8n", "ticker": None, "rss": None, "tier": 2},
        {"name": "Zapier AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Make (Integromat)", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_developer_tools": [
        {"name": "Hugging Face", "ticker": None, "rss": "https://huggingface.co/blog/feed.xml", "tier": 1},
        {"name": "Replicate", "ticker": None, "rss": None, "tier": 1},
        {"name": "Weights & Biases", "ticker": None, "rss": None, "tier": 1},
        {"name": "Scale AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Modal Labs", "ticker": None, "rss": None, "tier": 2},
        {"name": "Labelbox", "ticker": None, "rss": None, "tier": 2},
        {"name": "Snorkel AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Baseten", "ticker": None, "rss": None, "tier": 3},
        {"name": "Together AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Fireworks AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Anyscale", "ticker": None, "rss": None, "tier": 2},
        {"name": "Lightning AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Comet ML", "ticker": None, "rss": None, "tier": 3},
        {"name": "Activeloop", "ticker": None, "rss": None, "tier": 3},
        {"name": "Voxel51", "ticker": None, "rss": None, "tier": 3},
        {"name": "Argilla", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_coding": [
        {"name": "Cursor", "ticker": None, "rss": "https://www.cursor.com/blog/rss.xml", "tier": 1},
        {"name": "GitHub Copilot", "ticker": "MSFT", "rss": None, "tier": 1},
        {"name": "Cognition (Devin)", "ticker": None, "rss": None, "tier": 1},
        {"name": "Replit", "ticker": None, "rss": None, "tier": 1},
        {"name": "Codeium", "ticker": None, "rss": None, "tier": 2},
        {"name": "Poolside AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Magic.dev", "ticker": None, "rss": None, "tier": 2},
        {"name": "Tabnine", "ticker": None, "rss": None, "tier": 3},
        {"name": "Sourcegraph (Cody)", "ticker": None, "rss": None, "tier": 2},
        {"name": "JetBrains AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Windsurf (Codeium)", "ticker": None, "rss": None, "tier": 2},
        {"name": "Amazon CodeWhisperer", "ticker": "AMZN", "rss": None, "tier": 2},
        {"name": "Google Gemini Code", "ticker": "GOOGL", "rss": None, "tier": 2},
    ],
    "ai_search_research": [
        {"name": "Perplexity AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "You.com", "ticker": None, "rss": None, "tier": 2},
        {"name": "Exa AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Consensus", "ticker": None, "rss": None, "tier": 3},
        {"name": "Elicit", "ticker": None, "rss": None, "tier": 3},
        {"name": "Tavily", "ticker": None, "rss": None, "tier": 2},
        {"name": "Brave Search", "ticker": None, "rss": None, "tier": 2},
        {"name": "Metaphor Systems", "ticker": None, "rss": None, "tier": 3},
        {"name": "Bing AI (Microsoft)", "ticker": "MSFT", "rss": None, "tier": 1},
        {"name": "Phind", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_voice_multimodal": [
        {"name": "ElevenLabs", "ticker": None, "rss": None, "tier": 1},
        {"name": "Deepgram", "ticker": None, "rss": None, "tier": 2},
        {"name": "AssemblyAI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Cartesia", "ticker": None, "rss": None, "tier": 2},
        {"name": "Play.ht", "ticker": None, "rss": None, "tier": 3},
        {"name": "Resemble AI", "ticker": None, "rss": None, "tier": 3},
        {"name": "Whisper (OpenAI)", "ticker": None, "rss": None, "tier": 1},
        {"name": "Lovo AI", "ticker": None, "rss": None, "tier": 3},
        {"name": "Murf AI", "ticker": None, "rss": None, "tier": 3},
        {"name": "HeyGen", "ticker": None, "rss": None, "tier": 2},
        {"name": "Synthesia", "ticker": None, "rss": None, "tier": 2},
        {"name": "D-ID", "ticker": None, "rss": None, "tier": 2},
    ],
    "ai_rising_stars": [
        {"name": "Pika Labs", "ticker": None, "rss": None, "tier": 1},
        {"name": "Runway ML", "ticker": None, "rss": None, "tier": 1},
        {"name": "Midjourney", "ticker": None, "rss": None, "tier": 1},
        {"name": "Luma AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Physical Intelligence", "ticker": None, "rss": None, "tier": 1},
        {"name": "Figure AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Together AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Ideogram", "ticker": None, "rss": None, "tier": 2},
        {"name": "1X Technologies", "ticker": None, "rss": None, "tier": 2},
        {"name": "Character.AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Imbue", "ticker": None, "rss": None, "tier": 2},
        {"name": "Adept AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Stability AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Nous Research", "ticker": None, "rss": None, "tier": 2},
        {"name": "01.AI (Yi)", "ticker": None, "rss": None, "tier": 2},
        {"name": "Moonshot AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Sora (OpenAI)", "ticker": None, "rss": None, "tier": 1},
        {"name": "Kling AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Hailuo AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Rabbit Inc", "ticker": None, "rss": None, "tier": 2},
        {"name": "Humane", "ticker": None, "rss": None, "tier": 2},
        {"name": "Notion AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Mem AI", "ticker": None, "rss": None, "tier": 3},
        {"name": "Glean", "ticker": None, "rss": None, "tier": 2},
        {"name": "Sierra AI", "ticker": None, "rss": None, "tier": 2},
    ],
    "procurement_software": [
        {"name": "SAP Ariba", "ticker": "SAP", "rss": None, "tier": 1},
        {"name": "Coupa Software", "ticker": None, "rss": None, "tier": 1},
        {"name": "Ivalua", "ticker": None, "rss": None, "tier": 1},
        {"name": "Jaggaer", "ticker": None, "rss": None, "tier": 2},
        {"name": "GEP Worldwide", "ticker": None, "rss": None, "tier": 2},
        {"name": "Zycus", "ticker": None, "rss": None, "tier": 2},
        {"name": "Basware", "ticker": "BAS1V", "rss": None, "tier": 2},
        {"name": "Tradeshift", "ticker": None, "rss": None, "tier": 2},
        {"name": "Proactis", "ticker": None, "rss": None, "tier": 3},
        {"name": "Fairmarkit", "ticker": None, "rss": None, "tier": 2},
        {"name": "Zip", "ticker": None, "rss": None, "tier": 2},
        {"name": "Procurify", "ticker": None, "rss": None, "tier": 3},
        {"name": "Keelvar", "ticker": None, "rss": None, "tier": 2},
        {"name": "Bonfire", "ticker": None, "rss": None, "tier": 3},
        {"name": "Sievo", "ticker": None, "rss": None, "tier": 2},
        {"name": "SpendHQ", "ticker": None, "rss": None, "tier": 3},
        {"name": "Simfoni", "ticker": None, "rss": None, "tier": 3},
        {"name": "Scout RFP (Workday)", "ticker": "WDAY", "rss": None, "tier": 3},
        {"name": "Determine (Corcentric)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Rego Consulting", "ticker": None, "rss": None, "tier": 3},
        {"name": "Corcentric", "ticker": None, "rss": None, "tier": 2},
        {"name": "Vroozi", "ticker": None, "rss": None, "tier": 3},
        {"name": "Precoro", "ticker": None, "rss": None, "tier": 3},
        {"name": "Fraxion", "ticker": None, "rss": None, "tier": 3},
        {"name": "Tradogram", "ticker": None, "rss": None, "tier": 3},
        {"name": "ProcureDesk", "ticker": None, "rss": None, "tier": 3},
        {"name": "SpendBoss", "ticker": None, "rss": None, "tier": 3},
        {"name": "Xenett", "ticker": None, "rss": None, "tier": 3},
        {"name": "Graphite Connect", "ticker": None, "rss": None, "tier": 3},
        {"name": "Scoutbee", "ticker": None, "rss": None, "tier": 2},
    ],
    "logistics_supply_chain": [
        {"name": "DHL", "ticker": "DPSGY", "rss": None, "tier": 1},
        {"name": "FedEx", "ticker": "FDX", "rss": None, "tier": 1},
        {"name": "UPS", "ticker": "UPS", "rss": None, "tier": 1},
        {"name": "Maersk", "ticker": "AMKBY", "rss": None, "tier": 1},
        {"name": "Kuehne+Nagel", "ticker": "KHNGF", "rss": None, "tier": 1},
        {"name": "DB Schenker", "ticker": None, "rss": None, "tier": 1},
        {"name": "DSV", "ticker": "DSDVY", "rss": None, "tier": 1},
        {"name": "Ceva Logistics", "ticker": None, "rss": None, "tier": 2},
        {"name": "XPO Logistics", "ticker": "XPO", "rss": None, "tier": 2},
        {"name": "Flexport", "ticker": None, "rss": None, "tier": 2},
        {"name": "Expeditors International", "ticker": "EXPD", "rss": None, "tier": 2},
        {"name": "C.H. Robinson", "ticker": "CHRW", "rss": None, "tier": 2},
        {"name": "J.B. Hunt", "ticker": "JBHT", "rss": None, "tier": 2},
        {"name": "Ryder System", "ticker": "R", "rss": None, "tier": 2},
        {"name": "Geodis", "ticker": None, "rss": None, "tier": 2},
        {"name": "Panalpina (DSV)", "ticker": "DSDVY", "rss": None, "tier": 2},
        {"name": "CMA CGM", "ticker": None, "rss": None, "tier": 1},
        {"name": "Hapag-Lloyd", "ticker": "HLAGF", "rss": None, "tier": 2},
        {"name": "MSC Mediterranean", "ticker": None, "rss": None, "tier": 1},
        {"name": "Project44", "ticker": None, "rss": None, "tier": 2},
        {"name": "FourKites", "ticker": None, "rss": None, "tier": 2},
        {"name": "Descartes Systems", "ticker": "DSGX", "rss": None, "tier": 2},
        {"name": "Blue Yonder", "ticker": None, "rss": None, "tier": 2},
        {"name": "Kinaxis", "ticker": "KXS", "rss": None, "tier": 2},
        {"name": "E2open", "ticker": "ETWO", "rss": None, "tier": 2},
        {"name": "o9 Solutions", "ticker": None, "rss": None, "tier": 2},
        {"name": "Llamasoft (Coupa)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Freightos", "ticker": "CRGO", "rss": None, "tier": 3},
        {"name": "Forto", "ticker": None, "rss": None, "tier": 3},
        {"name": "sennder", "ticker": None, "rss": None, "tier": 3},
    ],
    "data_analytics_bi": [
        {"name": "Snowflake", "ticker": "SNOW", "rss": None, "tier": 1},
        {"name": "Databricks", "ticker": None, "rss": None, "tier": 1},
        {"name": "Palantir", "ticker": "PLTR", "rss": None, "tier": 1},
        {"name": "Tableau (Salesforce)", "ticker": "CRM", "rss": None, "tier": 1},
        {"name": "Power BI (Microsoft)", "ticker": "MSFT", "rss": None, "tier": 1},
        {"name": "Looker (Google)", "ticker": "GOOGL", "rss": None, "tier": 2},
        {"name": "Qlik", "ticker": None, "rss": None, "tier": 2},
        {"name": "MicroStrategy", "ticker": "MSTR", "rss": None, "tier": 2},
        {"name": "dbt Labs", "ticker": None, "rss": None, "tier": 2},
        {"name": "Fivetran", "ticker": None, "rss": None, "tier": 2},
        {"name": "Airbyte", "ticker": None, "rss": None, "tier": 2},
        {"name": "Starburst Data", "ticker": None, "rss": None, "tier": 2},
        {"name": "Grafana Labs", "ticker": None, "rss": None, "tier": 2},
        {"name": "Elastic", "ticker": "ESTC", "rss": None, "tier": 2},
        {"name": "Splunk (Cisco)", "ticker": "CSCO", "rss": None, "tier": 2},
        {"name": "DataRobot", "ticker": None, "rss": None, "tier": 3},
        {"name": "Alteryx", "ticker": "AYX", "rss": None, "tier": 3},
        {"name": "ThoughtSpot", "ticker": None, "rss": None, "tier": 3},
        {"name": "Sigma Computing", "ticker": None, "rss": None, "tier": 3},
        {"name": "Mode Analytics", "ticker": None, "rss": None, "tier": 3},
    ],
    "devops_cloud_tools": [
        {"name": "HashiCorp", "ticker": None, "rss": None, "tier": 2},
        {"name": "GitHub", "ticker": "MSFT", "rss": None, "tier": 1},
        {"name": "GitLab", "ticker": "GTLB", "rss": None, "tier": 2},
        {"name": "Docker", "ticker": None, "rss": None, "tier": 2},
        {"name": "Kubernetes (CNCF)", "ticker": None, "rss": None, "tier": 1},
        {"name": "Red Hat (IBM)", "ticker": "IBM", "rss": None, "tier": 2},
        {"name": "Datadog", "ticker": "DDOG", "rss": None, "tier": 1},
        {"name": "New Relic", "ticker": "NEWR", "rss": None, "tier": 2},
        {"name": "Dynatrace", "ticker": "DT", "rss": None, "tier": 2},
        {"name": "PagerDuty", "ticker": "PD", "rss": None, "tier": 2},
        {"name": "CircleCI", "ticker": None, "rss": None, "tier": 3},
        {"name": "JFrog", "ticker": "FROG", "rss": None, "tier": 2},
        {"name": "Terraform (HashiCorp)", "ticker": None, "rss": None, "tier": 2},
        {"name": "Pulumi", "ticker": None, "rss": None, "tier": 3},
        {"name": "Harness", "ticker": None, "rss": None, "tier": 2},
        {"name": "Argo CD (CNCF)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Rancher (SUSE)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Sumo Logic", "ticker": None, "rss": None, "tier": 3},
        {"name": "Honeycomb.io", "ticker": None, "rss": None, "tier": 3},
        {"name": "Temporal Technologies", "ticker": None, "rss": None, "tier": 3},
    ],
    "fintech_payments": [
        {"name": "Stripe", "ticker": None, "rss": None, "tier": 1},
        {"name": "Adyen", "ticker": "ADYEY", "rss": None, "tier": 1},
        {"name": "PayPal", "ticker": "PYPL", "rss": None, "tier": 1},
        {"name": "Visa", "ticker": "V", "rss": None, "tier": 1},
        {"name": "Mastercard", "ticker": "MA", "rss": None, "tier": 1},
        {"name": "Block (Square)", "ticker": "SQ", "rss": None, "tier": 1},
        {"name": "Klarna", "ticker": None, "rss": None, "tier": 2},
        {"name": "Checkout.com", "ticker": None, "rss": None, "tier": 2},
        {"name": "Brex", "ticker": None, "rss": None, "tier": 2},
        {"name": "Ramp", "ticker": None, "rss": None, "tier": 2},
        {"name": "Airwallex", "ticker": None, "rss": None, "tier": 2},
        {"name": "Wise", "ticker": "WISE", "rss": None, "tier": 2},
        {"name": "Plaid", "ticker": None, "rss": None, "tier": 2},
        {"name": "Marqeta", "ticker": "MQ", "rss": None, "tier": 2},
        {"name": "Nuvei", "ticker": "NVEI", "rss": None, "tier": 3},
        {"name": "Tipalti", "ticker": None, "rss": None, "tier": 2},
        {"name": "Codat", "ticker": None, "rss": None, "tier": 3},
        {"name": "Taxjar (Stripe)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Avalara (Astute)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Expensify", "ticker": "EXFY", "rss": None, "tier": 3},
    ],
    "telecommunications": [
        {"name": "AT&T", "ticker": "T", "rss": None, "tier": 1},
        {"name": "Verizon", "ticker": "VZ", "rss": None, "tier": 1},
        {"name": "Deutsche Telekom", "ticker": "DTEGY", "rss": None, "tier": 1},
        {"name": "Vodafone", "ticker": "VOD", "rss": None, "tier": 1},
        {"name": "T-Mobile", "ticker": "TMUS", "rss": None, "tier": 1},
        {"name": "Orange", "ticker": "ORAN", "rss": None, "tier": 2},
        {"name": "Telefónica", "ticker": "TEF", "rss": None, "tier": 2},
        {"name": "BT Group", "ticker": "BTGOF", "rss": None, "tier": 2},
        {"name": "SoftBank", "ticker": "SFTBY", "rss": None, "tier": 2},
        {"name": "NTT", "ticker": "NTTYY", "rss": None, "tier": 2},
        {"name": "KDDI", "ticker": "KDDIY", "rss": None, "tier": 3},
        {"name": "Telstra", "ticker": "TLSYY", "rss": None, "tier": 3},
        {"name": "Lumen Technologies", "ticker": "LUMN", "rss": None, "tier": 3},
        {"name": "Zayo Group", "ticker": None, "rss": None, "tier": 3},
        {"name": "DISH Network", "ticker": "DISH", "rss": None, "tier": 3},
        {"name": "Twilio", "ticker": "TWLO", "rss": None, "tier": 2},
        {"name": "Vonage (Ericsson)", "ticker": "ERIC", "rss": None, "tier": 3},
        {"name": "Bandwidth", "ticker": "BAND", "rss": None, "tier": 3},
    ],
    "robotics_drones": [
        {"name": "Boston Dynamics (Hyundai)", "ticker": "HYMTF", "rss": None, "tier": 1},
        {"name": "Figure AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Agility Robotics", "ticker": None, "rss": None, "tier": 2},
        {"name": "Apptronik", "ticker": None, "rss": None, "tier": 2},
        {"name": "Tesla Optimus", "ticker": "TSLA", "rss": None, "tier": 1},
        {"name": "DJI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Zipline", "ticker": None, "rss": None, "tier": 2},
        {"name": "Skydio", "ticker": None, "rss": None, "tier": 2},
        {"name": "Shield AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Joby Aviation", "ticker": "JOBY", "rss": None, "tier": 2},
        {"name": "Sarcos Robotics", "ticker": None, "rss": None, "tier": 3},
        {"name": "Vecna Robotics", "ticker": None, "rss": None, "tier": 3},
        {"name": "Locus Robotics", "ticker": None, "rss": None, "tier": 3},
        {"name": "6 River Systems (Shopify)", "ticker": None, "rss": None, "tier": 3},
        {"name": "Geek+ Robotics", "ticker": None, "rss": None, "tier": 3},
        {"name": "ABB Robotics", "ticker": "ABB", "rss": None, "tier": 2},
        {"name": "KUKA (Midea)", "ticker": None, "rss": None, "tier": 2},
        {"name": "Universal Robots (Teradyne)", "ticker": "TER", "rss": None, "tier": 2},
    ],
    "battery_ev": [
        {"name": "Tesla", "ticker": "TSLA", "rss": None, "tier": 1},
        {"name": "CATL", "ticker": "CATL", "rss": None, "tier": 1},
        {"name": "BYD", "ticker": "BYDDF", "rss": None, "tier": 1},
        {"name": "LG Energy Solution", "ticker": "LGCLF", "rss": None, "tier": 1},
        {"name": "Panasonic Energy", "ticker": "PCRFY", "rss": None, "tier": 2},
        {"name": "Samsung SDI", "ticker": "SSDIY", "rss": None, "tier": 2},
        {"name": "SK Innovation", "ticker": None, "rss": None, "tier": 2},
        {"name": "QuantumScape", "ticker": "QS", "rss": None, "tier": 2},
        {"name": "Solid Power", "ticker": "SLDP", "rss": None, "tier": 2},
        {"name": "Northvolt", "ticker": None, "rss": None, "tier": 2},
        {"name": "Rivian", "ticker": "RIVN", "rss": None, "tier": 2},
        {"name": "Lucid Motors", "ticker": "LCID", "rss": None, "tier": 2},
        {"name": "StoreDot", "ticker": None, "rss": None, "tier": 3},
        {"name": "SES AI", "ticker": "SES", "rss": None, "tier": 3},
        {"name": "Factorial Energy", "ticker": None, "rss": None, "tier": 3},
    ],
    "market_intelligence": [
        {"name": "Gartner", "ticker": "IT", "rss": None, "tier": 1},
        {"name": "Forrester Research", "ticker": "FORR", "rss": None, "tier": 2},
        {"name": "IDC", "ticker": None, "rss": None, "tier": 2},
        {"name": "Bloomberg", "ticker": None, "rss": None, "tier": 1},
        {"name": "S&P Global", "ticker": "SPGI", "rss": None, "tier": 1},
        {"name": "Moody's", "ticker": "MCO", "rss": None, "tier": 2},
        {"name": "Dun & Bradstreet", "ticker": "DNB", "rss": None, "tier": 2},
        {"name": "Wood Mackenzie", "ticker": None, "rss": None, "tier": 2},
        {"name": "IHS Markit (S&P)", "ticker": "SPGI", "rss": None, "tier": 2},
        {"name": "Refinitiv (LSEG)", "ticker": "LSEG", "rss": None, "tier": 2},
        {"name": "PitchBook", "ticker": None, "rss": None, "tier": 2},
        {"name": "CB Insights", "ticker": None, "rss": None, "tier": 2},
        {"name": "Crunchbase", "ticker": None, "rss": None, "tier": 3},
        {"name": "Dealroom", "ticker": None, "rss": None, "tier": 3},
        {"name": "Preqin", "ticker": None, "rss": None, "tier": 3},
    ],
}

# Flat list for bulk operations
ALL_SUPPLIERS = [s for category in SUPPLIERS.values() for s in category]

# Deduplicate by name
_seen = set()
_deduped = []
for s in ALL_SUPPLIERS:
    if s["name"] not in _seen:
        _seen.add(s["name"])
        _deduped.append(s)
ALL_SUPPLIERS = _deduped

# Tier-based groupings for scheduling
TIER_1 = [s for s in ALL_SUPPLIERS if s["tier"] == 1]
TIER_2 = [s for s in ALL_SUPPLIERS if s["tier"] == 2]
TIER_3 = [s for s in ALL_SUPPLIERS if s["tier"] == 3]

# Extra sources for AI category only
AI_EXTRA_SOURCES = [
    {"name": "Import AI Newsletter", "rss": "https://importai.substack.com/feed"},
    {"name": "The Batch (DeepLearning.AI)", "rss": "https://www.deeplearning.ai/the-batch/feed/"},
    {"name": "Hugging Face Blog", "rss": "https://huggingface.co/blog/feed.xml"},
    {"name": "arXiv cs.AI", "rss": "https://rss.arxiv.org/rss/cs.AI"},
    {"name": "arXiv cs.LG", "rss": "https://rss.arxiv.org/rss/cs.LG"},
    {"name": "TechCrunch AI", "rss": "https://techcrunch.com/category/artificial-intelligence/feed/"},
    {"name": "VentureBeat AI", "rss": "https://venturebeat.com/category/ai/feed/"},
]
