SUPPLIERS = {
    "semiconductors": [
        {"name": "NVIDIA", "ticker": "NVDA", "rss": "https://nvidianews.nvidia.com/releases.xml", "tier": 1},
        {"name": "Intel", "ticker": "INTC", "rss": "https://newsroom.intel.com/feed/", "tier": 1},
        {"name": "AMD", "ticker": "AMD", "rss": "https://ir.amd.com/news-releases/rss", "tier": 1},
        {"name": "Qualcomm", "ticker": "QCOM", "rss": "https://www.qualcomm.com/news/rss", "tier": 1},
        {"name": "Broadcom", "ticker": "AVGO", "rss": None, "tier": 1},
        {"name": "Texas Instruments", "ticker": "TXN", "rss": None, "tier": 2},
        {"name": "Analog Devices", "ticker": "ADI", "rss": None, "tier": 2},
        {"name": "Microchip Technology", "ticker": "MCHP", "rss": None, "tier": 2},
        {"name": "NXP Semiconductors", "ticker": "NXPI", "rss": None, "tier": 2},
        {"name": "STMicroelectronics", "ticker": "STM", "rss": None, "tier": 2},
        {"name": "Infineon Technologies", "ticker": "IFNNY", "rss": None, "tier": 2},
        {"name": "Renesas Electronics", "ticker": "RNECY", "rss": None, "tier": 2},
        {"name": "MediaTek", "ticker": "MDTKF", "rss": None, "tier": 2},
        {"name": "TSMC", "ticker": "TSM", "rss": None, "tier": 1},
        {"name": "GlobalFoundries", "ticker": "GFS", "rss": None, "tier": 2},
        {"name": "UMC", "ticker": "UMC", "rss": None, "tier": 3},
        {"name": "Tower Semiconductor", "ticker": "TSEM", "rss": None, "tier": 3},
        {"name": "onsemi", "ticker": "ON", "rss": None, "tier": 2},
        {"name": "Skyworks Solutions", "ticker": "SWKS", "rss": None, "tier": 2},
        {"name": "Qorvo", "ticker": "QRVO", "rss": None, "tier": 2},
        {"name": "Marvell Technology", "ticker": "MRVL", "rss": None, "tier": 2},
        {"name": "Lattice Semiconductor", "ticker": "LSCC", "rss": None, "tier": 3},
        {"name": "Monolithic Power Systems", "ticker": "MPWR", "rss": None, "tier": 3},
        {"name": "Silicon Labs", "ticker": "SLAB", "rss": None, "tier": 3},
        {"name": "MaxLinear", "ticker": "MXL", "rss": None, "tier": 3},
        {"name": "Semtech", "ticker": "SMTC", "rss": None, "tier": 3},
        {"name": "Cirrus Logic", "ticker": "CRUS", "rss": None, "tier": 3},
        {"name": "MACOM Technology", "ticker": "MTSI", "rss": None, "tier": 3},
        {"name": "Entegris", "ticker": "ENTG", "rss": None, "tier": 3},
        {"name": "Kulicke & Soffa", "ticker": "KLIC", "rss": None, "tier": 3},
    ],
    "memory_storage": [
        {"name": "Samsung Electronics", "ticker": "SSNLF", "rss": "https://news.samsung.com/global/feed", "tier": 1},
        {"name": "SK Hynix", "ticker": "HXSCF", "rss": None, "tier": 1},
        {"name": "Micron Technology", "ticker": "MU", "rss": None, "tier": 1},
        {"name": "Kingston Technology", "ticker": None, "rss": None, "tier": 2},
        {"name": "Western Digital", "ticker": "WDC", "rss": None, "tier": 2},
        {"name": "Seagate Technology", "ticker": "STX", "rss": None, "tier": 2},
        {"name": "Kioxia", "ticker": None, "rss": None, "tier": 2},
        {"name": "Pure Storage", "ticker": "PSTG", "rss": None, "tier": 2},
        {"name": "NetApp", "ticker": "NTAP", "rss": None, "tier": 2},
        {"name": "Hitachi Vantara", "ticker": None, "rss": None, "tier": 3},
        {"name": "Transcend", "ticker": None, "rss": None, "tier": 3},
        {"name": "ADATA", "ticker": None, "rss": None, "tier": 3},
    ],
    "networking": [
        {"name": "Cisco Systems", "ticker": "CSCO", "rss": "https://newsroom.cisco.com/feed/", "tier": 1},
        {"name": "Juniper Networks", "ticker": "JNPR", "rss": None, "tier": 2},
        {"name": "Arista Networks", "ticker": "ANET", "rss": None, "tier": 1},
        {"name": "Palo Alto Networks", "ticker": "PANW", "rss": None, "tier": 1},
        {"name": "Fortinet", "ticker": "FTNT", "rss": None, "tier": 2},
        {"name": "F5 Networks", "ticker": "FFIV", "rss": None, "tier": 2},
        {"name": "Extreme Networks", "ticker": "EXTR", "rss": None, "tier": 3},
        {"name": "HPE Aruba", "ticker": "HPE", "rss": None, "tier": 2},
        {"name": "Nokia", "ticker": "NOK", "rss": "https://www.nokia.com/about-us/news/releases/feed/", "tier": 2},
        {"name": "Ericsson", "ticker": "ERIC", "rss": None, "tier": 2},
        {"name": "CommScope", "ticker": "COMM", "rss": None, "tier": 2},
        {"name": "Ciena", "ticker": "CIEN", "rss": None, "tier": 2},
        {"name": "Lumentum", "ticker": "LITE", "rss": None, "tier": 3},
        {"name": "Viavi Solutions", "ticker": "VIAV", "rss": None, "tier": 3},
        {"name": "ADTRAN", "ticker": "ADTN", "rss": None, "tier": 3},
        {"name": "Calix", "ticker": "CALX", "rss": None, "tier": 3},
        {"name": "Ribbon Communications", "ticker": "RBBN", "rss": None, "tier": 3},
        {"name": "Spirent Communications", "ticker": "SPT", "rss": None, "tier": 3},
        {"name": "Cradlepoint", "ticker": None, "rss": None, "tier": 3},
        {"name": "Cambium Networks", "ticker": "CMBM", "rss": None, "tier": 3},
    ],
    "cloud_infrastructure": [
        {"name": "Amazon Web Services", "ticker": "AMZN", "rss": "https://aws.amazon.com/blogs/aws/feed/", "tier": 1},
        {"name": "Microsoft Azure", "ticker": "MSFT", "rss": "https://azure.microsoft.com/en-us/blog/feed/", "tier": 1},
        {"name": "Google Cloud", "ticker": "GOOGL", "rss": "https://cloud.google.com/feeds/gcp-release-notes.xml", "tier": 1},
        {"name": "Oracle Cloud", "ticker": "ORCL", "rss": None, "tier": 2},
        {"name": "IBM Cloud", "ticker": "IBM", "rss": None, "tier": 2},
        {"name": "Cloudflare", "ticker": "NET", "rss": "https://blog.cloudflare.com/rss/", "tier": 1},
        {"name": "Fastly", "ticker": "FSLY", "rss": None, "tier": 2},
        {"name": "Akamai", "ticker": "AKAM", "rss": None, "tier": 2},
        {"name": "DigitalOcean", "ticker": "DOCN", "rss": None, "tier": 2},
        {"name": "Vultr", "ticker": None, "rss": None, "tier": 3},
        {"name": "Hetzner", "ticker": None, "rss": None, "tier": 3},
        {"name": "OVHcloud", "ticker": "OVH", "rss": None, "tier": 3},
        {"name": "CoreWeave", "ticker": None, "rss": None, "tier": 1},
        {"name": "Lambda Labs", "ticker": None, "rss": None, "tier": 2},
    ],
    "servers_hardware": [
        {"name": "Dell Technologies", "ticker": "DELL", "rss": "https://www.dell.com/en-us/blog/feed/", "tier": 1},
        {"name": "HP Inc", "ticker": "HPQ", "rss": None, "tier": 2},
        {"name": "HPE", "ticker": "HPE", "rss": None, "tier": 1},
        {"name": "Lenovo", "ticker": "LNVGY", "rss": None, "tier": 2},
        {"name": "Supermicro", "ticker": "SMCI", "rss": None, "tier": 1},
        {"name": "Inspur", "ticker": None, "rss": None, "tier": 2},
        {"name": "Fujitsu", "ticker": "FJTSY", "rss": None, "tier": 2},
        {"name": "Hitachi", "ticker": "HTHIY", "rss": None, "tier": 2},
        {"name": "NEC", "ticker": "NIPNF", "rss": None, "tier": 3},
        {"name": "Gigabyte Technology", "ticker": None, "rss": None, "tier": 3},
        {"name": "ASRock Rack", "ticker": None, "rss": None, "tier": 3},
        {"name": "Wiwynn", "ticker": None, "rss": None, "tier": 3},
        {"name": "QCT (Quanta Cloud)", "ticker": None, "rss": None, "tier": 3},
    ],
    "contract_manufacturing": [
        {"name": "Foxconn", "ticker": "HNHPF", "rss": None, "tier": 1},
        {"name": "Pegatron", "ticker": None, "rss": None, "tier": 2},
        {"name": "Quanta Computer", "ticker": "QUCPF", "rss": None, "tier": 2},
        {"name": "Compal Electronics", "ticker": None, "rss": None, "tier": 2},
        {"name": "Wistron", "ticker": None, "rss": None, "tier": 2},
        {"name": "Jabil", "ticker": "JBL", "rss": None, "tier": 2},
        {"name": "Flex Ltd", "ticker": "FLEX", "rss": None, "tier": 2},
        {"name": "Celestica", "ticker": "CLS", "rss": None, "tier": 2},
        {"name": "Sanmina", "ticker": "SANM", "rss": None, "tier": 3},
        {"name": "Benchmark Electronics", "ticker": "BHE", "rss": None, "tier": 3},
        {"name": "Plexus Corp", "ticker": "PLXS", "rss": None, "tier": 3},
        {"name": "Fabrinet", "ticker": "FN", "rss": None, "tier": 3},
    ],
    "cables_connectors": [
        {"name": "Amphenol", "ticker": "APH", "rss": None, "tier": 2},
        {"name": "TE Connectivity", "ticker": "TEL", "rss": None, "tier": 2},
        {"name": "Molex", "ticker": None, "rss": None, "tier": 2},
        {"name": "Samtec", "ticker": None, "rss": None, "tier": 3},
        {"name": "Hirose Electric", "ticker": "HRELF", "rss": None, "tier": 3},
        {"name": "Phoenix Contact", "ticker": None, "rss": None, "tier": 3},
        {"name": "Belden", "ticker": "BDC", "rss": None, "tier": 3},
        {"name": "Panduit", "ticker": None, "rss": None, "tier": 3},
        {"name": "Bourns", "ticker": None, "rss": None, "tier": 3},
        {"name": "Vishay Intertechnology", "ticker": "VSH", "rss": None, "tier": 3},
    ],
    "power_energy": [
        {"name": "Eaton", "ticker": "ETN", "rss": None, "tier": 2},
        {"name": "Schneider Electric", "ticker": "SBGSF", "rss": None, "tier": 1},
        {"name": "Vertiv", "ticker": "VRT", "rss": None, "tier": 1},
        {"name": "Delta Electronics", "ticker": "DELTF", "rss": None, "tier": 2},
        {"name": "ABB", "ticker": "ABB", "rss": None, "tier": 2},
        {"name": "Bel Fuse", "ticker": "BELFA", "rss": None, "tier": 3},
        {"name": "Vicor Corporation", "ticker": "VICR", "rss": None, "tier": 3},
        {"name": "Mean Well", "ticker": None, "rss": None, "tier": 3},
    ],
    "test_measurement": [
        {"name": "Keysight Technologies", "ticker": "KEYS", "rss": None, "tier": 2},
        {"name": "Teradyne", "ticker": "TER", "rss": None, "tier": 2},
        {"name": "National Instruments", "ticker": "NATI", "rss": None, "tier": 2},
        {"name": "Rohde & Schwarz", "ticker": None, "rss": None, "tier": 2},
        {"name": "Anritsu", "ticker": None, "rss": None, "tier": 3},
        {"name": "Cohu", "ticker": "COHU", "rss": None, "tier": 3},
        {"name": "Advantest", "ticker": "ATEYY", "rss": None, "tier": 3},
    ],
    "cybersecurity": [
        {"name": "CrowdStrike", "ticker": "CRWD", "rss": "https://www.crowdstrike.com/blog/feed/", "tier": 1},
        {"name": "SentinelOne", "ticker": "S", "rss": None, "tier": 1},
        {"name": "Zscaler", "ticker": "ZS", "rss": None, "tier": 1},
        {"name": "Okta", "ticker": "OKTA", "rss": None, "tier": 1},
        {"name": "Check Point Software", "ticker": "CHKP", "rss": None, "tier": 2},
        {"name": "Varonis Systems", "ticker": "VRNS", "rss": None, "tier": 2},
        {"name": "Tenable Holdings", "ticker": "TENB", "rss": None, "tier": 2},
        {"name": "Rapid7", "ticker": "RPD", "rss": None, "tier": 2},
        {"name": "Qualys", "ticker": "QLYS", "rss": None, "tier": 2},
        {"name": "Darktrace", "ticker": "DARK", "rss": None, "tier": 2},
        {"name": "Illumio", "ticker": None, "rss": None, "tier": 3},
        {"name": "Recorded Future", "ticker": None, "rss": None, "tier": 2},
    ],
    "optical_fiber": [
        {"name": "Corning", "ticker": "GLW", "rss": None, "tier": 2},
        {"name": "CommScope", "ticker": "COMM", "rss": None, "tier": 2},
        {"name": "Prysmian", "ticker": "PRYMF", "rss": None, "tier": 2},
        {"name": "Nexans", "ticker": "NEXNY", "rss": None, "tier": 3},
        {"name": "Sumitomo Electric", "ticker": "SMTOF", "rss": None, "tier": 3},
        {"name": "Coherent Corp", "ticker": "COHR", "rss": None, "tier": 2},
    ],
    "cooling_thermal": [
        {"name": "Nidec Corporation", "ticker": "NJDCY", "rss": None, "tier": 3},
        {"name": "Delta Electronics", "ticker": "DELTF", "rss": None, "tier": 2},
        {"name": "Boyd Corporation", "ticker": None, "rss": None, "tier": 3},
        {"name": "Laird Thermal Systems", "ticker": None, "rss": None, "tier": 3},
        {"name": "Liqtech International", "ticker": "LIQT", "rss": None, "tier": 3},
    ],
    "distributors_resellers": [
        {"name": "Arrow Electronics", "ticker": "ARW", "rss": None, "tier": 1},
        {"name": "Avnet", "ticker": "AVT", "rss": None, "tier": 1},
        {"name": "TD SYNNEX", "ticker": "SNX", "rss": None, "tier": 1},
        {"name": "Ingram Micro", "ticker": None, "rss": None, "tier": 1},
        {"name": "CDW Corporation", "ticker": "CDW", "rss": None, "tier": 2},
        {"name": "Insight Direct", "ticker": "NSIT", "rss": None, "tier": 2},
        {"name": "SHI International", "ticker": None, "rss": None, "tier": 2},
        {"name": "Wesco International", "ticker": "WCC", "rss": None, "tier": 2},
        {"name": "Digi-Key Electronics", "ticker": None, "rss": None, "tier": 2},
        {"name": "Mouser Electronics", "ticker": None, "rss": None, "tier": 2},
        {"name": "Newark (Farnell)", "ticker": None, "rss": None, "tier": 3},
        {"name": "RS Components", "ticker": None, "rss": None, "tier": 3},
    ],
    "enterprise_software": [
        {"name": "Microsoft", "ticker": "MSFT", "rss": "https://news.microsoft.com/feed/", "tier": 1},
        {"name": "SAP", "ticker": "SAP", "rss": None, "tier": 2},
        {"name": "Oracle", "ticker": "ORCL", "rss": None, "tier": 2},
        {"name": "Salesforce", "ticker": "CRM", "rss": None, "tier": 2},
        {"name": "ServiceNow", "ticker": "NOW", "rss": None, "tier": 2},
        {"name": "Workday", "ticker": "WDAY", "rss": None, "tier": 2},
        {"name": "Adobe", "ticker": "ADBE", "rss": None, "tier": 2},
        {"name": "Autodesk", "ticker": "ADSK", "rss": None, "tier": 3},
        {"name": "PTC", "ticker": "PTC", "rss": None, "tier": 3},
        {"name": "Dassault Systemes", "ticker": "DASTY", "rss": None, "tier": 3},
        {"name": "ANSYS", "ticker": "ANSS", "rss": None, "tier": 3},
    ],
    "industrial_automation": [
        {"name": "Siemens", "ticker": "SIEGY", "rss": "https://press.siemens.com/global/en/pressreleases/rss", "tier": 2},
        {"name": "Rockwell Automation", "ticker": "ROK", "rss": None, "tier": 2},
        {"name": "Honeywell", "ticker": "HON", "rss": None, "tier": 2},
        {"name": "Yokogawa Electric", "ticker": "YOKEY", "rss": None, "tier": 3},
        {"name": "Fanuc", "ticker": "FANUY", "rss": None, "tier": 3},
        {"name": "Keyence", "ticker": "KYCCF", "rss": None, "tier": 3},
        {"name": "Cognex", "ticker": "CGNX", "rss": None, "tier": 3},
        {"name": "Zebra Technologies", "ticker": "ZBRA", "rss": None, "tier": 3},
        {"name": "Advantech", "ticker": "ATECF", "rss": None, "tier": 3},
    ],
    "ai_foundation_labs": [
        {"name": "Anthropic", "ticker": None, "rss": "https://www.anthropic.com/rss.xml", "tier": 1},
        {"name": "OpenAI", "ticker": None, "rss": "https://openai.com/blog/rss.xml", "tier": 1},
        {"name": "Google DeepMind", "ticker": "GOOGL", "rss": "https://deepmind.google/blog/rss.xml", "tier": 1},
        {"name": "Meta AI", "ticker": "META", "rss": "https://ai.meta.com/blog/rss/", "tier": 1},
        {"name": "Mistral AI", "ticker": None, "rss": "https://mistral.ai/news/rss", "tier": 1},
        {"name": "xAI (Grok)", "ticker": None, "rss": None, "tier": 1},
        {"name": "Cohere", "ticker": None, "rss": None, "tier": 1},
        {"name": "AI21 Labs", "ticker": None, "rss": None, "tier": 2},
        {"name": "Inflection AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Aleph Alpha", "ticker": None, "rss": None, "tier": 2},
    ],
    "ai_infrastructure_chips": [
        {"name": "Groq", "ticker": None, "rss": None, "tier": 1},
        {"name": "Cerebras Systems", "ticker": None, "rss": None, "tier": 1},
        {"name": "SambaNova Systems", "ticker": None, "rss": None, "tier": 2},
        {"name": "Tenstorrent", "ticker": None, "rss": None, "tier": 1},
        {"name": "Graphcore", "ticker": None, "rss": None, "tier": 2},
        {"name": "d-Matrix", "ticker": None, "rss": None, "tier": 2},
        {"name": "Etched", "ticker": None, "rss": None, "tier": 2},
        {"name": "Hailo Technologies", "ticker": None, "rss": None, "tier": 2},
        {"name": "Rain AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Kneron", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_agents_orchestration": [
        {"name": "LangChain", "ticker": None, "rss": "https://blog.langchain.dev/rss/", "tier": 1},
        {"name": "LlamaIndex", "ticker": None, "rss": None, "tier": 1},
        {"name": "CrewAI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Relevance AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Beam AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Dust", "ticker": None, "rss": None, "tier": 2},
        {"name": "Superagent", "ticker": None, "rss": None, "tier": 3},
        {"name": "Wordware", "ticker": None, "rss": None, "tier": 2},
    ],
    "ai_developer_tools": [
        {"name": "Hugging Face", "ticker": None, "rss": "https://huggingface.co/blog/feed.xml", "tier": 1},
        {"name": "Replicate", "ticker": None, "rss": None, "tier": 1},
        {"name": "Modal Labs", "ticker": None, "rss": None, "tier": 2},
        {"name": "Weights & Biases", "ticker": None, "rss": None, "tier": 1},
        {"name": "Scale AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Labelbox", "ticker": None, "rss": None, "tier": 2},
        {"name": "Snorkel AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Baseten", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_coding": [
        {"name": "Cursor", "ticker": None, "rss": "https://www.cursor.com/blog/rss.xml", "tier": 1},
        {"name": "GitHub Copilot", "ticker": "MSFT", "rss": None, "tier": 1},
        {"name": "Replit", "ticker": None, "rss": None, "tier": 1},
        {"name": "Codeium", "ticker": None, "rss": None, "tier": 2},
        {"name": "Poolside AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Magic.dev", "ticker": None, "rss": None, "tier": 2},
        {"name": "Cognition (Devin)", "ticker": None, "rss": None, "tier": 1},
        {"name": "Tabnine", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_search_research": [
        {"name": "Perplexity AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "You.com", "ticker": None, "rss": None, "tier": 2},
        {"name": "Exa AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Consensus", "ticker": None, "rss": None, "tier": 3},
        {"name": "Elicit", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_voice_multimodal": [
        {"name": "ElevenLabs", "ticker": None, "rss": None, "tier": 1},
        {"name": "Deepgram", "ticker": None, "rss": None, "tier": 2},
        {"name": "AssemblyAI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Cartesia", "ticker": None, "rss": None, "tier": 2},
        {"name": "Play.ht", "ticker": None, "rss": None, "tier": 3},
        {"name": "Resemble AI", "ticker": None, "rss": None, "tier": 3},
    ],
    "ai_rising_stars": [
        {"name": "Pika Labs", "ticker": None, "rss": None, "tier": 1},
        {"name": "Runway ML", "ticker": None, "rss": None, "tier": 1},
        {"name": "Midjourney", "ticker": None, "rss": None, "tier": 1},
        {"name": "Ideogram", "ticker": None, "rss": None, "tier": 2},
        {"name": "Luma AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "Physical Intelligence", "ticker": None, "rss": None, "tier": 1},
        {"name": "Figure AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "1X Technologies", "ticker": None, "rss": None, "tier": 2},
        {"name": "Character.AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Imbue", "ticker": None, "rss": None, "tier": 2},
        {"name": "Adept AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Stability AI", "ticker": None, "rss": None, "tier": 2},
        {"name": "Nous Research", "ticker": None, "rss": None, "tier": 2},
        {"name": "Together AI", "ticker": None, "rss": None, "tier": 1},
        {"name": "01.AI (Yi)", "ticker": None, "rss": None, "tier": 2},
        {"name": "Moonshot AI", "ticker": None, "rss": None, "tier": 2},
    ],
}

# Flat list for bulk operations
ALL_SUPPLIERS = [s for category in SUPPLIERS.values() for s in category]

# Tier-based groupings for scheduling
TIER_1 = [s for s in ALL_SUPPLIERS if s["tier"] == 1]
TIER_2 = [s for s in ALL_SUPPLIERS if s["tier"] == 2]
TIER_3 = [s for s in ALL_SUPPLIERS if s["tier"] == 3]

# Extra sources for AI category only
AI_EXTRA_SOURCES = [
    {"name": "Import AI Newsletter", "rss": "https://importai.substack.com/feed"},
    {"name": "The Batch (DeepLearning.AI)", "rss": "https://www.deeplearning.ai/the-batch/feed/"},
    {"name": "Hugging Face Blog", "rss": "https://huggingface.co/blog/feed.xml"},
    {"name": "arXiv cs.AI", "rss": "https://rss.arxiv.org/rss/cs.AI"},
    {"name": "arXiv cs.LG", "rss": "https://rss.arxiv.org/rss/cs.LG"},
    {"name": "TechCrunch AI", "rss": "https://techcrunch.com/category/artificial-intelligence/feed/"},
    {"name": "VentureBeat AI", "rss": "https://venturebeat.com/category/ai/feed/"},
]
